name: flutter_login_microsoft
description: A login widget with login/signup functionalities to help speed up development
version: 1.0.14
author: NearHuscarl <near.huscarl@gmail.com>
homepage: https://github.com/NearHuscarl/flutter_login

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  provider: ^4.0.2
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1
  
  quiver: ^2.0.5
  chopper: ^3.0.2
  chopper_generator: ^3.0.4
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  shared_preferences: ^0.5.7+3
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


flutter:
  
  assets:
    - assets/images/ecorp.png
    - assets/images/logo_branco_brlog.png
