name: flutter_login_microsoft
description: A login widget with login/signup functionalities to help speed up development
version: 1.0.14
author: NearHuscarl <near.huscarl@gmail.com>
homepage: https://github.com/NearHuscarl/flutter_login

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  provider: ^5.0.0
  transformer_page_view: ^0.1.6
  another_flushbar: ^1.10.23
  
  quiver: ^3.0.1
  chopper: ^4.0.1
  chopper_generator: ^4.0.1
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10


flutter:
  
  assets:
    - assets/images/ecorp.png
    - assets/images/logo_branco_brlog.png
